# Font settings
font_family      JetBrainsMono Nerd Font
font_size        12.0

# Window appearance
background_opacity 0.9
cursor_shape beam
enable_audio_bell no

# Keybindings
map ctrl+shift+t new_tab
map ctrl+shift+w close_tab
map ctrl+shift+enter new_window

# Theme (example)
# foreground #d0d0d0
# background #1e1e2e

enabled_layouts splits
# Split window horizontally
map alt+) launch --location=hsplit --type=window

# Split window vertically
map alt+( launch --location=vsplit



# BEGIN_KITTY_THEME
# Solarized Dark - Patched
include current-theme.conf
# END_KITTY_THEME